import streamlit as st
def page_2():
    st.title("favorite Cartoon")
    st.write('Halaman ini Menampilkan beberapa kartun favorit. Enjoy For Watching Guys!')
    st.write('Unicorn Academy')
    st.image("unicorn academy.jpeg", width=200)
    st.write('Musim gugur ini, serial animasi dan franchise petualangan orisinal Netflix, yang diproduksi oleh Spin Master Entertainment, akan membawa penonton ke dunia magis saat mereka mengikuti Sophia dalam perjalanannya dari biasa menjadi luar biasa saat ia menemukan takdirnya sebagai pengendara unicorn. Unicorn Academy adalah sekolah asrama impian setiap anak. Terletak di Pulau Unicorn, Sophia dan siswa baru lainnya harus terikat dengan unicorn mereka untuk membuka kekuatan magis mereka. Hanya dengan cara ini para siswa akan belajar untuk menjadi pelindung pulau dan keajaibannya – sambil menyeimbangkan tugas di kelas, menavigasi persahabatan dan persaingan, serta menghadapi cobaan dan kesengsaraan dalam kehidupan remaja pada umumnya.')
    st.video('https://youtu.be/kqUs5c4DWu8?si=NC67e-uTdMl60JWW')
    st.video('https://youtu.be/8Y4xXodzmPU?si=4unPH9fio487WlqH')
    st.write('Encanto')
    st.image("encanto.jpeg", width=200)
    st.write('Encanto menceritakan kisah keluarga yang bernama Madrigal, yang tinggal di kota ajaib di pegunungan Kolombia. Keajaiban Encanto telah memberkati setiap anak dalam keluarga dengan hadiah unik dari kekuatan super hingga kekuatan untuk menyembuhkan setiap anak kecuali satu, Mirabel. Tetapi ketika dia menemukan bahwa sihir di sekitar Encanto dalam bahaya, Mirabel memutuskan bahwa dia satu-satunya Madrigal biasa, mungkin saja menjadi harapan terakhir keluarganya.')
    st.video('https://youtu.be/hrMxx8EV4JU?si=X70_-myhIXEzZREj')
    st.video('https://youtu.be/_fzJoBWa-PQ?si=zc6L-cf05aXxPv1Q')
    st.write('Moana')
    st.image("moana.jpeg", width=200)
    st.write('Kartun ini bercerita tentang Moana, putri berkemauan keras dari seorang kepala desa Polinesia, yang dipilih oleh lautan itu sendiri untuk menyatukan kembali peninggalan mistis dewi Te Fiti. Ketika kutukan menyerang pulau itu, Moana berlayar mencari Maui, seorang dewa legendaris, dengan harapan mengembalikan peninggalan tersebut ke dewi Te Fiti dan menyelamatkan rakyatnya.')
    st.video('https://youtu.be/RTWhvp_OD6s?si=2w6tRtu5fpMK43-M')
    st.video('https://youtu.be/NPUUcP2rab8?si=bYy9BSwLH0tu-o_w')